name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install required library
      run: ./configure/linux.sh
    - name: make
      run: cmake .
    - name: Build project
      run: make
    - name: Run tests
      run: make test
